### ISSUE TITLE
[Question] How to change exposed"Firmware" value?

### ISSUE THREAD

**Issue by lboue** [YOGYUI/matter-esp32-dcmotor#7]
Hello,

Do you know which field and which cluster this "Firmware" value corresponds to in Matter fabric and iOS?
I couldn't find it in the project's source code. Is it in the SDK source code?

![fan_firmware](https://github.com/YOGYUI/matter-esp32-dcmotor/assets/938089/3f2bbfa7-5f08-45cb-858c-aae49416c27c)

Regards

**Comment by YOGYUI** [comment]
@lboue You can see `PROJECT_VER_NUMBER` definition in [CMakeLists.txt](https://github.com/YOGYUI/matter-esp32-dcmotor/blob/main/CMakeLists.txt).
```
cmake_minimum_required(VERSION 3.5)

set(ENV{ESP_MATTER_DEVICE_PATH} $ENV{ESP_MATTER_PATH}/device_hal/device/esp32_devkit_c)
set(PROJECT_VER "1.0.0.0")
set(PROJECT_VER_NUMBER 20231127)
```

**Comment by lboue** [comment]
Thanks 👍
